
import "./globals.css";
import Navbar from "@/component/layout/navbar";
import Footer from "@/component/layout/footer";
import SmoothScroll from "@/component/smooth/smoothScroll";
import AOSProvider from "./AosProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" font-intel">
        <AOSProvider>   
        <Navbar/>
       <SmoothScroll>{children}</SmoothScroll> 
       <Footer/>
       </AOSProvider>
      </body>
    </html>
  );
}




